apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-otelcol
  namespace: collector
spec:
  image: otel/opentelemetry-collector-contrib:0.104.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: receiver-otelcol-collector.receiver.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: "debug"
      extensions: []
      pipelines:
        logs: 
          processors: []
          receivers: [otlp]
          exporters: [otlp,debug]
