apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    nsSelector: example-tenant-2
  name: example-tenant-ns-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: example-collector
spec:
  debug: true
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: example-collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    nsSelector: example-tenant-1
  name: example-tenant-ns-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: example-collector
  name: example-tenant
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-1
  logSourceNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-1
