apiVersion: v1
kind: Namespace
metadata:
  labels:
    nsSelector: example-tenant-1
  name: example-tenant-ns-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: example-collector
  name: example-tenant
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-1
  logSourceNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-sample-1
  namespace: example-tenant-ns-1
spec:
  ottl: "route()"
  outputs:
    - name: otlp-test-output-1
      namespace: collector
---
apiVersion: v1
kind: Secret
metadata:
  name: otlp-test-output-1-basicauth-token-secret
  namespace: collector
type: Opaque
data:
  username: dXNlcg== # user
  password: cGFzcw== # pass
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: otlp-test-output-1
  namespace: collector
spec:
  authentication:
    basicauth:
      secretRef:
        name: otlp-test-output-1-basicauth-token-secret
        namespace: collector
  otlp:
    endpoint: receiver-otelcol-collector.receiver.svc.cluster.local:4317
    tls:
      insecure: false
      insecure_skip_verify: true
